### ISSUE TITLE
请问RAG所用的txt文档是如何获取的呢？

### ISSUE THREAD

**Issue by foss12138** [SocialAI-tianji/Tianji#54]
你好~我在跟着项目做的时候，发现RAG的数据是从hugging face上获取的，请问其中的TXT数据是如何爬取并且规则化的呢？以及vx群二维码已过期，还请更新一下，谢谢~

**Comment by sanbuphy** [comment]
你好，你可以参考这里的代码进行复现：https://github.com/SocialAI-tianji/Tianji/tree/main/tools/rag
已经更新群二维码

**Comment by sanbuphy** [comment]
视频相关数据参考 https://github.com/SocialAI-tianji/Tianji/tree/main/tools/finetune/everything2data/video2json

**Comment by foss12138** [comment]
好的谢谢！！！
