### ISSUE TITLE
您好，在使用RAG的时候出现了这样的错误，如图，请问应该怎么解决呢？

### ISSUE THREAD

**Issue by ltc0** [SocialAI-tianji/Tianji#55]
![image](https://github.com/user-attachments/assets/2e15d535-bc38-4b8a-85af-dd1af6b4f231)

**Comment by sanbuphy** [comment]
你好,可以分享一下是怎么启动的,是在自己的本地电脑上吗

**Comment by ltc0** [comment]
在云服务器上。执行了这个之后pip install -e .，现在可以正常运行了

**Comment by xjyisok** [comment]
# 运行prompt webui前端
python3 run/tianji_prompt_webui.py

# 运行agent前端
streamlit run run/metagpt_webui.py

# 运行langchain前端
python run/demo_rag_langchain_onlinellm.py
你好我看文档里面执行的这三个文件好像只有最后一个有，其他两个好像没了，还有我执行最后一个的时候在数据生成的时候显示我没有设置zhipuapi-key但是我在配置文件中是设置了的

**Comment by ltc0** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by ltc0** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by xjyisok** [comment]
不是你抄送给我干嘛，我踏马又不是开发者，给你们开源人闹麻了



---原始邮件---
发件人: "Ruo ***@***.***&gt;
发送时间: 2026年6月3日(周三) 晚上6:48
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [SocialAI-tianji/Tianji] 您好，在使用RAG的时候出现了这样的错误，如图，请问应该怎么解决呢？ (Issue #55)


fatumax left a comment (SocialAI-tianji/Tianji#55)
 
@ltc0 @sanbuphy @xjyisok
 
看到这个项目的情况（在没有任何版本发布的情况下，一周增长了 3685 Star，大部分账号只 Star 了不超过三个仓库，而且这三个仓库之间有明显关联），我想说句实话：我也曾经动过刷星的念头。
 
那是几个月前的时候。我维护的一个开源项目做了大半年，自认为质量不差，但 Star 数一直在两位数。看着隔壁质量不如自己的项目凭一波刷星上了 Trending，说不嫉妒是假的。
 
我甚至去搜了刷星的价格——几百块就能买一千个，看起来又快又便宜。那个下午我手指悬在付款按钮上面犹豫了很久。
 
最后没买。原因也简单：我问了自己一个问题——如果被发现了怎么办？
 
不是怕被骂，是怕我这么多年建立起来的技术信誉毁于一旦。那几百块钱的风险，我赌不起。
 
后来那个项目确实慢慢涨起来了。虽然到现在也没多少 Star，但每一个都是真的，我看着心里踏实。
 
写这些不是为了标榜自己多有道德。只是想告诉维护者：我理解你的处境，但你选的这条路不通。现在回头还来得及。
  
赶紧止损，把假星删掉
 
写个 postmortem 告诉大家发生了什么
 
把精力放回到代码和文档上
  
写这些不是为了搞事，而是真心希望项目能好。
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications, keep track of coding agent tasks and review pull requests on the go with GitHub Mobile for iOS and Android. Download it today!

**Comment by xjyisok** [comment]
不是你抄送给我干嘛，我踏马又不是开发者，给你们开源人闹麻了



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2026年6月3日(周三) 晚上6:49
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [SocialAI-tianji/Tianji] 您好，在使用RAG的时候出现了这样的错误，如图，请问应该怎么解决呢？ (Issue #55)


ltc0 left a comment (SocialAI-tianji/Tianji#55)
 这是来自QQ邮箱的假期自动回复邮件。 
 &nbsp; 
 您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications, keep track of coding agent tasks and review pull requests on the go with GitHub Mobile for iOS and Android. Download it today!
