### ISSUE TITLE
环境变量

### ISSUE THREAD

**Issue by xjyisok** [SocialAI-tianji/Tianji#57]
你好环境变量中HF_HOME='temp/huggingface_cache/'这里的HF_HOME指的是什么，我该如何设置

**Comment by sanbuphy** [comment]
这个的意思是 huggingface 模型的缓存地址，所有被触发下载的 huggingface 模型将会下载到此处。
如果不设置可能会被下载到C盘或者系统目录；如果设置（如当前环境是在该文件夹的 temp 路径） 则表示下载到指定的当前文件夹地址。

**Comment by xjyisok** [comment]
不是你抄送给我干嘛，我踏马又不是开发者，给你们开源人闹麻了



---原始邮件---
发件人: "Ting ***@***.***&gt;
发送时间: 2026年6月3日(周三) 晚上6:52
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [SocialAI-tianji/Tianji] 环境变量 (Issue #57)


kafakigang left a comment (SocialAI-tianji/Tianji#57)
 
@xjyisok @sanbuphy
 
最近几天涌进来一大波假账号给你打星，特征太明显了——空壳号扎堆出现，时间线高度集中。
 
这么搞对社区公平性是一种伤害，对那些认真做项目的开发者也不尊重。
 
请你：
  
排查清理掉那些虚假的 star
 
给出一个公开声明
 
别再玩这种数字游戏了
  
开源圈子不大，名声坏了就很难挽回，三思而行。
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications, keep track of coding agent tasks and review pull requests on the go with GitHub Mobile for iOS and Android. Download it today!
