### ISSUE TITLE
Time

### ISSUE THREAD

**Issue by xjyisok** [SocialAI-tianji/Tianji#58]
初始化数据库要多久

**Comment by sanbuphy** [comment]
取决于cpu，10分钟左右，快的话5分钟内

**Comment by xjyisok** [comment]
不是你抄送给我干嘛，我踏马又不是开发者，给你们开源人闹麻了



---Original---
From: "Yunqi ***@***.***&gt;
Date: Wed, Jun 3, 2026 18:55 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [SocialAI-tianji/Tianji] Time (Issue #58)


wolfguidepink left a comment (SocialAI-tianji/Tianji#58)
 
@xjyisok @sanbuphy
 
不想再解释什么了。唯一的活动就是给本项目点了星。证据确凿。处理不处理随你，但大家都看在眼里。
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications, keep track of coding agent tasks and review pull requests on the go with GitHub Mobile for iOS and Android. Download it today!
